apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-cost-agent-config
  namespace: system
data:
  COST_CONSUMER_URL: "http://cost-event-consumer.cost-mgmt.svc:8020/api/v1/events"
  CLUSTER_ID: "my-cluster"
  TENANT_ID: ""
  HEARTBEAT_INTERVAL: "60s"
  NODE_RECONCILE_INTERVAL: "5m"
  BATCH_SIZE: "100"
  BATCH_INTERVAL: "5s"
  EXCLUDE_NAMESPACES: "kube-system"
